const MAX=15,$=s=>document.querySelector(s);let sources={video:null,audio:null},timer;
const video=$('#video'),audio=$('#audio'),start=$('#start'),end=$('#end');
function setStatus(s){$('#status').textContent=s}
function playable(files,type){const formats=type==='video'?/MPEG4|h\.264|Matroska|Ogg Video/i:/VBR MP3|Ogg Vorbis|FLAC|WAVE|MP3/i;return files.filter(f=>formats.test(f.format||'')&&!f.private).slice(0,12)}
async function search(type){const q=$('#'+type+'Query').value.trim();if(!q)return;setStatus('Searching Internet Archive…');const mediatype=type==='video'?'movies':'audio';const url='https://archive.org/advancedsearch.php?q='+encodeURIComponent('title:('+q+') AND mediatype:'+mediatype)+'&fl[]=identifier&fl[]=title&rows=12&output=json';const j=await fetch(url).then(r=>r.json());const box=$('#'+type+'Results');box.replaceChildren();for(const doc of j.response.docs){const b=document.createElement('button');b.textContent=doc.title||doc.identifier;b.onclick=()=>chooseItem(type,doc.identifier,b);box.append(b)}setStatus('Choose a result.')}
async function chooseItem(type,id,button){setStatus('Loading item files…');const m=await fetch('https://archive.org/metadata/'+encodeURIComponent(id)).then(r=>r.json());const files=playable(m.files||[],type);if(!files.length){setStatus('No browser-playable file found in that item.');return}const f=files[0],url='https://archive.org/download/'+encodeURIComponent(id)+'/'+f.name.split('/').map(encodeURIComponent).join('/');setSource(type,url,{provider:'internet-archive',identifier:id,file:f.name,title:m.metadata?.title||button.textContent,licenseurl:m.metadata?.licenseurl||null});}
function setSource(type,url,meta){sources[type]={url,meta};if(type==='video')video.src=url;else audio.src=url;setStatus(type+' selected.');}
$('#videoUpload').onchange=e=>{const f=e.target.files[0];if(f)setSource('video',URL.createObjectURL(f),{provider:'local-upload',name:f.name})};
$('#audioUpload').onchange=e=>{const f=e.target.files[0];if(f)setSource('audio',URL.createObjectURL(f),{provider:'local-upload',name:f.name})};
document.querySelectorAll('[data-search]').forEach(b=>b.onclick=()=>search(b.dataset.search).catch(e=>setStatus(e.message)));
video.onloadedmetadata=()=>{const d=Number.isFinite(video.duration)?video.duration:MAX;start.max=d;end.max=d;start.value=0;end.value=Math.min(MAX,d);syncTrim()};
function syncTrim(changed){let a=+start.value,b=+end.value;if(changed==='start'&&b-a>MAX)b=a+MAX;if(changed==='end'&&b-a>MAX)a=b-MAX;if(b<a)b=a;start.value=Math.max(0,a);end.value=Math.min(+end.max,b);$('#startOut').value=(+start.value).toFixed(1)+'s';$('#endOut').value=(+end.value).toFixed(1)+'s'}
start.oninput=()=>syncTrim('start');end.oninput=()=>syncTrim('end');$('#mix').oninput=e=>$('#mixOut').value=Math.round(e.target.value*100)+'%';
$('#preview').onclick=async()=>{if(!sources.video)return setStatus('Add a video first.');clearInterval(timer);video.currentTime=+start.value;if(sources.audio){audio.currentTime=0;audio.volume=+$('#mix').value;await audio.play()}await video.play();timer=setInterval(()=>{if(video.currentTime>=+end.value){video.pause();audio.pause();clearInterval(timer);setStatus('ACT preview complete.')}},50)};
function manifest(){return{schema_version:'1.0.0',type:'ACT',brand:'Infinity ®',duration_seconds:+(+end.value-+start.value).toFixed(2),trim:{start_seconds:+start.value,end_seconds:+end.value,max_seconds:MAX},video:sources.video?.meta||null,soundtrack:sources.audio?.meta||null,mix:{music_volume:+$('#mix').value,dialogue_priority:true},rights:{verified:$('#rights').checked,status:$('#rights').checked?'user-verified':'verification-required'},created_at:new Date().toISOString(),status:'append-only'}}
$('#download').onclick=()=>{const blob=new Blob([JSON.stringify(manifest(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='infinity-act-manifest.json';a.click();URL.revokeObjectURL(a.href)};